### ISSUE TITLE
I have some question..

### ISSUE THREAD

**Issue by bemoregt** [tashrifbillah/Object-Detection#1]
Hi, @tashrifbillah 

Thank you  your great source code!
I have some question..

What is the merits of using RL for object detection?
Is that no need to making box annotation? 
Is that no need Big data for training?

I wonder ..

Thanks in advance ~

from @bemoregt.

**Comment by tashrifbillah** [comment]
The [paper](http://slazebni.cs.illinois.edu/publications/iccv15_active.pdf) should tell the merit of RL in object detection.

This was a just a semester long course project during my Masters. It would be good if we could annotate the boxes with labels for each object we were detecting. However, I did not have time for that.

See the README.md for [training data](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/):

Hope this helps.

**Comment by bemoregt** [comment]
@tashrifbillah ,

Many Thanks
